---
- hosts: servers
  become: yes
  become_method: sudo

  tasks:
  - name: Install DHCP
    package:
      name: dhcp
      state: present

  - name: Copy config file over
    copy:
      src: 'dhcpd.conf'
      dest: '/etc/dhcp/dhcpd.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'

  - name: Make sure the service is started
    systemd:
      name: dhcpd.service
      enabled: yes
      state: restarted

